[package]
name = "site"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
tera = "1"
glob = "0.3"
rayon = "1"
serde = "1"
serde_derive = "1"
sass-rs = "0.2"

errors = { path = "../errors" }
config = { path = "../config" }
utils = { path = "../utils" }
templates = { path = "../templates" }
front_matter = { path = "../front_matter" }
library = { path = "../library" }

[dev-dependencies]
tempfile = "3"
